# Generated by Django 3.2 on 2021-04-14 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('major', models.CharField(max_length=200)),
                ('stdnum', models.CharField(max_length=200, unique=True)),
                ('name', models.IntegerField(max_length=200)),
                ('email', models.EmailField(max_length=500, unique=True)),
            ],
        ),
    ]
