# Generated by Django 3.2 on 2021-04-30 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_alter_member_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='major',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='member',
            name='name',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='stdnum',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
