# Generated by Django 3.2 on 2021-05-05 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_auto_20210430_0834'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
