# Generated by Django 3.2 on 2021-05-07 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0005_member_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='email_hash',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
    ]
