# Generated by Django 3.2 on 2021-05-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0006_auto_20210507_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='email_hash',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
