# Generated by Django 3.2 on 2021-05-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0008_auto_20210513_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='info_hash',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
